

lbl_anrr = {
    'country_name': 'Country name',
    'wbcode': 'World Bank country code',
    'year': 'Year (from 1960 to 2010)',
    'gdppercapitaconstant2000us': 'GDP per capita (constant 2000 US$, from World Bank)',
    'lp_bl': 'Percentage of population with at most primary education (Barro-Lee)',
    'ls_bl': 'Percentage of population with at most secondary education (Barro-Lee)',
    'lh_bl': 'Percentage of population with tertiary education (Barro-Lee)',
    'taxratio': 'Tax revenue as a share of GDP (from Hendrix)',
    'region': 'Geographical region',
    'wbcode2': 'Generated numeric country code',
    'demCGV': 'Democracy measure by CGV',
    'demBMR': 'Democracy measure by BMR',
    'yeardem': 'Identifier for a democratization during this year',
    'yearrev': 'Identifier for a reversal to autocracy during this year',
    'secenr': 'Secondary enrollment from World bank',
    'prienr': 'Primary enrollment from World Bank',
    'tradewb': 'Exports plus Imports as a share of GDP from World Bank',
    'mortnew': 'Child mortality per 1000 births from World Bank',
    'ginv': 'Gross investment as a share of GDP',
    'rtfpna': 'TFP at constant national prices (2005=1) from PWT',
    'y': 'log of GDP per capita in 2000 constant dollars (multiplied by a 100)',
    'dem': 'Democracy measure by ANRR',
    'InitReg': 'Democratic status after independence or in 1960',
    'unrest': 'Occurrence of events of unrest (from Banks CNTS)',
    'loginvpc': 'log investment (multiplied by 100)',
    'ltfp': 'log TFP (multiplied by 100)',
    'ltrade2': 'lof of trade (multiplied by 100)',
    'lprienr': 'lof of primary enrollment (multiplied by 100)',
    'lsecenr': 'log of secondary enrollment (multiplied by 100)',
    'lgov': 'log of taxes to GDP (multiplied by a 100)',
    'lmort': 'log of child mortality rate (multiplied by a 100)',
    'unrestn': 'Likelihood of unrest (0-100 scale)',
    'demFH': 'democracy measure based on Freedom House',
    'demPOL': 'democracy measure based on Polity IV',
    'demPS': 'democracy measure by PS (1960)',
    'demPOL_xconst': 'dummy for constraints on executive (based on polity)',
    'demPOL_parcomp': 'dummy for competitiveness of participation (based on polity)',
    'demPOL_exrec': 'dummy for quality of executive recruitment process (based on Polity)',
    'demFH_pr': 'Dummy for political rights (based on Freedom House)',
    'demFH_cl': 'Dummy for civil liberties (based on Freedom House)',
    'demevent': 'Event of democratization',
    'revevent': 'Event of reversal to autocracy',
    'democ': 'Cummulative number of democratizations',
    'rever': 'Cummulative number of reversals',
    'demext': 'Democratic status at beginning of sample',
    'regionINITREG': 'Region/Initial regime at start of sample cells',
    'demreg': 'Average democracy in the region*initial regime (leaving own country out)',
    'tradewbreg': 'Regional trade',
    'unrestreg': 'Regional unrest',
    'yreg': 'Regional GDP per capita',
    'region60': 'Region/Democratic in 1960 cells',
    'regionDA': 'Region/Always democratic cells',
    'regionREG': 'Region/Detailed regime in 1960 cells',
    'demreg60': 'Average democracy in the region*initial regim (using regime in 1960, jackniffed)',
    'demregDA': 'Average democracy in the region*initial regim (using always democracy, jackniffe',
    'demregREGIME': 'Average democracy in the region*initial regime (detailed regimes, jackniffed)',
    'gdp1960': 'GDP per capita in 1960 from Madisson',
    'region_initreg_year': 'Region/Initial regime/year cells',
    'incomequint50s_year': 'Income quintiles in 50s/year cells',
    'sov1': 'Soviets post 89',
    'sov2': 'Soviets post 90',
    'sov3': 'Soviets post 91',
    'sov4': 'Soviets post 92',
    'marketref': 'Index of market reforms (1960)',
    'gfa': 'sum) gfa',
    'nfa': 'sum) nfa',
    'totalassets': 'sum) totalassets',
    'totalliabilities': 'sum) totalliabilities',
    'nfagdp': 'mean) nfagdp',
    'nfagdpreg': 'nfagdpreg',
    'incomequint50s_year1': 'incomequint50 1',
    'incomequint50s_year2': 'incomequint50 2',
    'quintile50s': 'quintile50s',
    'dquint1': 'quintile50s== 1.0000',
    'dquint2': 'quintile50s== 2.0000',
    'dquint3': 'quintile50s== 3.0000',
    'dquint4': 'quintile50s== 4.0000',
    'dquint5': 'quintile50s== 5.0000',
    'country': 'Country Name',
    'areakm2': 'Area in km2',
    'cen_lat': 'latitude of country centroid',
    'cen_lon': 'longitude of country centroid',
    'elev': 'mean m above sea level',
    'distcr': 'mean distance to coast or river',
    'distc': 'mean distance to coast',
    'distr': 'mean distance to river',
    'tropicar': '% land area in geographical tropics',
    'troppop': 'pop (95) in geographical tropics',
    'lc100km': 'area 100km from icefree coast',
    'lcr100km': 'area 100km from icefree coast or sea-nav. river',
    'pop95': '1995 pop (from GPWv2)',
    'pdenpavg': 'typical pop density experienced',
    'pop100km': 'pop (95) 100km from icefree coast',
    'pop100cr': 'pop (95) 100km from icefree coast or sea-nav. river',
    'cen_c': 'dist centroid to coast(km)',
    'cen_cr': 'dist centroid to coast/riv (km)',
    'polity': 'polity',
    'xrreg': 'xrreg',
    'xrcomp': 'xrcomp',
    'xropen': 'xropen',
    'xconst': 'xconst',
    'parreg': 'parreg',
    'parcomp': 'parcomp',
    'exrec': 'exrec',
    'exconst': 'exconst',
    'polcomp': 'polcomp',
    'polity2_aug': 'polity2_aug',
    'independent': 'independent',
    'transition': 'transition',
    'interruption': 'interruption',
    'interregnum': 'interregnum',
    'pr': 'pr',
    'cl': 'cl',
    'pr_aug': 'pr_aug',
    'cl_aug': 'cl_aug',
    'demt': 'demt',
    'polity2': 'polity2',
    'status': 'status',
    'NAME': 'NAME',
    'LON': 'LON',
    'LAT': 'LAT',
    '_ID': 'ID variable',
    'GDPpercapitaconstantLCUN': 'GDP per capita (constant LCU) [NY.GDP.PCAP.KN]',
    'rgdpl2': 'rgdpl2',
    'rgdpna_full': 'rgdpna_full',
    'PopulationtotalSPPOPTOTL': 'Population, total [SP.POP.TOTL]',
    'Populationages014oftotal': 'Population ages 0-14 (% of total) [SP.POP.0014.TO.ZS]',
    'Populationages1564oftota': 'Population ages 15-64 (% of total) [SP.POP.1564.TO.ZS]'
}

# Variable labels
lbl_ar = { 
    # COLONIES
    ###########
    'baseco':       'dummy for former colonies included in the base N=64 sample',
    'f_brit':       'BritishColony(Flopsexpsn)',
    'f_french':     'FrenchColony(Flopsexpans)',
    'rich4':        'dummy=1 for neo-europes',
    'sjlofr':       'French legal orgin recoded',
    'excolony':     '=1 if was colony FLOPS definiti',

    # MORTALITY
    ##############
    'logem4':       'log of mortality rate (IV)',
    'mortality':    'mortality measure (deaths per 1000 soldiers) from Appendix Table A2, AJR',
    'imputedmort':  'imputed mortality rate from logem4 measure (=exp(logem4))',
    'extmort4':     'corrected mortality (AJR)',

    # SETTLEMENT PATTERNS
    ######################
    'euro1900':     'european settlements in 1900',

    # INSTITUTIONS
    ###############
    'currentinst':  'IFC ease of doing business index/rank, 2012 (** our measure)',
    'avexpr':       'avg. risk of expropriation, 1985-1995',
    'cons00a':      'constraint on executive in 1900',
    'cons1':        'constraint on executive in 1st year of independence',
    'indtime':      'years independent: 1995 minus firstyr',
    'democ00a':     'democracy in 1900',
    'democ1':       'democracy in first year of independence',

    # ECONOMIC PERFORMANCE
    #######################
    'logpgp95':     'log GDP per capita PPP in 1995, World Bank ',
    'loghjypl':     'log output per worker in 1988 (US normalized to 1), Hall & Jones',
    'logpgp12':     'log GDP per capital PPP in 2012, World Bank (** our measure)',

    # GEOGRAPHY/NATURAL ENVIRONMENT
    ###############################
    'lat_abst':     'Abs(latitude of capital)/90',
    'meantemp':     'mean temperature (McArthur and Sachs)',
    'lt100km':      'amount of territory within 100 km of the coast (McArthur and Sachs)',
    'latabs':       'absolute latitude (McArthur and Sachs)',
    'africa':       'dummy=1 for Africa',
    'asia':         'dummy=1 for Asia',
    'other':        'dummy=1 if not in Asia, Africa, or the Americas',
    'temp1':        'temperature: 1',
    'temp2':        'temperature: 2',
    'temp3':        'temperature: 3',
    'temp4':        'temperature: 4',
    'temp5':        'temperature: 5',
    'humid1':       'humidity: 1',
    'humid2':       'humidity: 2',
    'humid3':       'humidity: 3',
    'humid4':       'humidity: 4',
    'steplow':      'soil: steplow' ,
    'deslow':       'soil: deslow' ,
    'stepmid':      'soil: stepmid' ,
    'desmid':       'soil: desmid' ,
    'drystep':      'soil: drystep' ,
    'drywint':      'soil: drywint',

    'landlock':     '=1 if landlocked',
    'goldm':        'Natural minerals: gold',
    'iron':         'Natural mineral: iron',
    'silv':         'Natural mineral: silver',
    'zinc':         'Natural mineral: zinc',
    'oilres':       'oil reserves ',

    # SOCIAL/CULTURAL ENVIRONMENT
    #############################
    'catho80':      'catholic as %pop 1980 wce95',
    'muslim80':     'muslims as % pop 1980 wce95',
    'no_cpm80':     '100-Cath-Protest-Muslim in 1980',
    'edes1975':     '% of European descent in 1975',
    'avelf':        'ethno fract avg 5indic east_lev',

    # DISEASES
    ##########
    'malfal94':     'Falciparum malaria index 1994',
    'yellow':       '=1 if vector yellow fever present today',
    'leb95':        'life expectancy at birth (1995)',
    'imr95':        'infant mortality rate (1995)',

    # NOT DESCRIBED 
    ###############
    'inst.age.1900': 'inst.age.1900'
}


